services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8002
    #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env
    ports:
      - "8002:8002"
    command: sh -c "cd /code/src && uv run uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - ./src:/code/src:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: docker-compose.yaml